# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#    resolvers:
#        default:
#            web_path: ~
#        default:
#                    web_path:
#                        web_root: "%kernel.root_dir%/.."
#                        cache_prefix: "media/cache"

    filter_sets:
        cache: ~

        squared_thumbnail_small:
#            jpeg_quality:          40
#            png_compression_level: 9
            filters:
                  thumbnail:
                                size:          [200, 200]
                                mode:          outbound
                                allow_upscale: true
#                  post_processors:
#                                optipng: { strip_all: true, level: 5 }
#                                pngquant: { quality: "75-85" }