#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: index/index.html.twig
        _locale: '%locale%'
